---
title: "Coral MuSE"
author: "LMM, EM, MV, AC, et al"
date: "14 de enero de 2019"
output: 
  html_document:
    code_download: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages

```{r packages}
library(tidyverse)
library(magrittr)
library(vegan)
library(cowplot)
library(jtools)
library(trafo)
library(colorblindr)
source('r/MSEgroup.r')
source('r/BootResampler.R')
```

```{r}
if (!dir.exists('analysis/figures')){
dir.create('analysis/figures')}
```


# Field data

```{r field dataset}
reef_pts <- read.csv('data/Points_Transect_BenthicSubstrate.csv', 
                     check.names = F, stringsAsFactors = T)
#
groups <- reef_pts[,2:6]
#
available_files <- reef_pts[reef_pts$File %in%
                        list.files("data/transects"), ]

coral_spp <- read.csv('data/caribbean_spp.csv')
```

```{r coral absolute cover, warning=FALSE}
coral_cover <-   reef_pts %>% 
  select(-c(1:7)) %>% 
  select(one_of(as.character(coral_spp[coral_spp$Group.ID %in% c(1:9), "Species.name"]))) %>% 
  divide_by(375) %>% 
  multiply_by(100) %>%
  mutate(dummy = 1) %>%   #add a dummy variable
  vegdist(method = "bray")
```

```{r mse and tidy format}
raw_mse <- coral_cover %>% 
  MSEgroup.d(groups$Site) %>% 
  data.frame() %>% 
  mutate(sites = rownames(.)) %>% 
  gather(-sites, key = 'replicate', value = "MSE") %>% 
  separate(replicate, 
           into = c('value', 'replicate'), 
           sep = '[.]') %>% 
  spread(value, MSE) %>% 
  filter(replicate != 1) %>% #exclude 1st transect
  mutate(replicate = as.numeric(replicate), 
         sites =  as.factor(sites)) %>% 
  rename(mse = means) %>% 
  filter(sites != 'Petaquire' | replicate != 4) %>% 
  mutate(replicate = replace(replicate, 
                             sites == 'Petaquire' & replicate == 3, 4)
         )
```

```{r}
field_mse <- raw_mse %>% 
  filter(replicate == 4) %>% 
  left_join(groups[groups$Transect == 't3',], 
            by = c('sites' = 'Site')) %>% 
  mutate(range = upper-lower) %>% 
  mutate(prop = range/mse) %>% 
  arrange(Locality)

field_mse$sites <- factor(field_mse$sites, 
                           levels = field_mse$sites[order(field_mse$Locality)])
```


# Achieved precision

```{r}
ggplot(field_mse, aes(x = fct_rev(sites), 
                      y = mse, 
                      fill = Locality)
       ) + 
  geom_bar(stat = 'identity') +
  geom_errorbar(aes(ymin = lower, ymax = upper), 
                width= .1) +
  coord_flip() +
  geom_hline(yintercept = mean(field_mse$mse),
             alpha=0.25,
             size = 2) +
  labs(x = "Sites", y = 'Multivariate standard error') +
  scale_fill_OkabeIto() 

  #ggsave('analysis/figures/fig01.png')
```


Now we choose the set of sites for resampling

```{r}
field_mse %>% 
  arrange(desc(mse)) %>% 
  filter(range %in% head(range, 12))
```


# Transects


#Dataset construction

```{r}
NTransects <- 20
NQuadrats <- seq(5, 25, 5)
NPoints <- seq(25, 75, 25)

DF <- NULL

for(i in 1:length(NTransects)) {
  for(j in 1:length(NQuadrats)) {
    for(k in 1:length(NPoints)) {
      
      boot_DF <- BootResampler(DataFrame = available_files, 
                    nbTransects = NTransects[i], 
                    nbQuadrats = NQuadrats[j], 
                    nbPoints = NPoints[k], 
                    transects_folder = "data/transects/", 
                    SpMatrix_Path = coral_spp, 
                    randomseed = 1)
      
      group_DF <- boot_DF %>% 
        select(2:7)
      
      mse_DF <- boot_DF %>% 
        select(-c(1:7)) %>%
        select(one_of(as.character(coral_spp[coral_spp$Group.ID %in% c(1:9), "Species.name"]))) %>% 
        divide_by(375) %>% 
        multiply_by(100) %>%
        mutate(dummy = 1) %>%   #add a dummy variable
        vegdist(method = "bray") %>% 
        MSEgroup.d(group_DF$Site) %>% 
        data.frame() %>% 
        mutate(sites = rownames(.)) %>% 
        gather(-sites, key = 'replicate', 
               value = "MSE") %>% 
        separate(replicate, 
                 into = c('value', 'replicate'), 
                 sep = '[.]') %>% 
        spread(value, MSE) %>% 
        filter(replicate != 1) %>% #exclude 1st transect
        mutate(replicate = as.numeric(replicate), 
               sites =  as.factor(sites)) %>% 
        rename(mse = means) %>% 
        mutate(ntransects = NTransects[i], 
               nquads = NQuadrats[j], 
               npoints = NPoints[k])
      
      DF <- bind_rows(DF, mse_DF)
      
      print(paste("Transects: ", NTransects[i], 
                  "| Quadrats: ", NQuadrats[j], 
                  "| Points: ", NPoints[k]))
      
    }
  }
}
```

```{r}
DF <- DF %>%
  mutate(range = upper-lower) %>% 
  mutate(prop = range/mse) %>% 
  rename(transects = replicate, quadrats = nquads, points = npoint)
```

#Comparison

We can compare if the MuSE behaves the same in the field and bootstrapped datasets

```{r comparison}
set1 <- raw_mse %>% 
          select(mse, sites, replicate) %>%
          rename(transects = replicate) %>% 
          mutate(type='field')

set2 <- DF %>% 
  select(mse, sites, transects) %>% 
  mutate(type='boot') 
  
bind_rows(set1, set2) %>% 
  filter(sites =='Salinas') %>% #choose an specific site
  ggplot(aes(x = transects, y = mse, shape = type, color = type)) + 
  geom_point()
```

# Plots

##  Global

```{r sites as replicates}
ggplot(DF, aes(x = transects, y = mse)) +
  geom_point() +
  facet_grid(quadrats~points) +
  theme(panel.grid.major = element_line(colour='gray90'))
```

##  Particular cases

```{r Case Punta Cruz}
DF %>% 
  filter(sites %in% c('Punta Cruz'))%>% 
  mutate(points = as.factor(points), 
         quadrats = as.factor(quadrats)) %>% 
  ggplot(aes(x = transects, y = mse)) +
  geom_point() +
  geom_ribbon(aes(ymin = lower, ymax = upper), 
              linetype = 2, 
              alpha = 0.1) +
  facet_grid(quadrats~points) +
  theme(panel.grid.major = element_line(colour='gray90'))
```

# Regression

```{r regression}
mod <- lm(mse~points*quadrats*transects, data = DF)

#plot(mod)
```

```{r}
diagnostics(trafo_lm(mod))

bc_mod <- trafo_lm(mod)

summary(bc_mod$trafo_mod)

plot_summs(bc_mod$trafo_mod)  
#ggsave('analysis/figures/fig02.png')
```
